apiVersion: v1
kind: Service
metadata:
  name: node-app-service
spec:
  selector:
    app: node-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 8080
      name: 5000-8080
  type: ClusterIP
status: 
  loadBalancer: {}