apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service-nodeport
spec:
  selector:
    app: node-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 8080
      name: 5000-8080
  type: NodePort
status: 
  loadBalancer: {}