apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: node-app
  name: node-app
spec:
  containers:
  - image: quay.io/emishra/node-app:v0.1
    name: node-app
    ports:
    - containerPort: 80
    resources: {}
    env:
    - name: NAME
      value: "Ekta Mishra"
    - name: COMPANY
      value: "Red Hat"
status: {}