apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: node-app-rs
  labels:
    app: node-app-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: quay.io/emishra/node-app:v0.1
        env:
        - name: NAME
          value: "Ekta Mishra"
        - name: COMPANY
          value: "Red Hat"
  